# Generated by Django 5.1.5 on 2025-01-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_review', to='kurs_app.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='kurs_app.course'),
        ),
    ]
