# Generated by Django 5.1.5 on 2025-01-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursereview',
            old_name='stars',
            new_name='rating',
        ),
    ]
