# Generated by Django 5.1.5 on 2025-01-21 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='options',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='options',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kurs_app.questions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='text',
            field=models.CharField(default=1, max_length=56),
            preserve_default=False,
        ),
    ]
