# Generated by Django 5.1.5 on 2025-01-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0002_rename_stars_coursereview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('client', 'Client'), ('courier', 'Courier')], default='client', max_length=16),
        ),
    ]
