# Generated by Django 5.1.5 on 2025-01-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0003_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='education',
            field=models.CharField(choices=[('высший', 'Высший'), ('средний ', 'Средний'), ('низкий', 'Низкий')], default='средний', max_length=32),
        ),
    ]
