# Generated by Django 5.1.5 on 2025-01-21 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_app', '0003_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificate', to='kurs_app.course'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('student', 'Student'), ('teacger', 'Teacher')], default='student', max_length=16),
        ),
    ]
